# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/P30/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/P30/proprietary/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin \
    vendor/huawei/P30/proprietary/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin \
    vendor/huawei/P30/proprietary/etc/firmware/S_ANDRO_SFL.ini:system/etc/firmware/S_ANDRO_SFL.ini \
    vendor/huawei/P30/proprietary/etc/firmware/WIFI_RAM_CODE_6580:system/etc/firmware/WIFI_RAM_CODE_6580 \
    vendor/huawei/P30/proprietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
    vendor/huawei/P30/proprietary/etc/firmware/catcher_filter_1_2g_n.bin:system/etc/firmware/catcher_filter_1_2g_n.bin \
    vendor/huawei/P30/proprietary/etc/firmware/catcher_filter_1_wg_n.bin:system/etc/firmware/catcher_filter_1_wg_n.bin \
    vendor/huawei/P30/proprietary/etc/firmware/modem_1_2g_n.img:system/etc/firmware/modem_1_2g_n.img \
    vendor/huawei/P30/proprietary/etc/firmware/modem_1_wg_n.img:system/etc/firmware/modem_1_wg_n.img \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v1_coeff.bin:system/etc/firmware/mt6580/mt6580_fm_v1_coeff.bin \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v1_patch.bin:system/etc/firmware/mt6580/mt6580_fm_v1_patch.bin \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v2_coeff.bin:system/etc/firmware/mt6580/mt6580_fm_v2_coeff.bin \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v2_patch.bin:system/etc/firmware/mt6580/mt6580_fm_v2_patch.bin \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v3_coeff.bin:system/etc/firmware/mt6580/mt6580_fm_v3_coeff.bin \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v3_patch.bin:system/etc/firmware/mt6580/mt6580_fm_v3_patch.bin \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v4_coeff.bin:system/etc/firmware/mt6580/mt6580_fm_v4_coeff.bin \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v4_patch.bin:system/etc/firmware/mt6580/mt6580_fm_v4_patch.bin \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v5_coeff.bin:system/etc/firmware/mt6580/mt6580_fm_v5_coeff.bin \
    vendor/huawei/P30/proprietary/etc/firmware/mt6580/mt6580_fm_v5_patch.bin:system/etc/firmware/mt6580/mt6580_fm_v5_patch.bin \
    vendor/huawei/P30/proprietary/etc/firmware/pcm_deepidle.bin:system/etc/firmware/pcm_deepidle.bin \
    vendor/huawei/P30/proprietary/etc/firmware/pcm_sodi.bin:system/etc/firmware/pcm_sodi.bin \
    vendor/huawei/P30/proprietary/etc/firmware/pcm_suspend.bin:system/etc/firmware/pcm_suspend.bin \
    vendor/huawei/P30/proprietary/vendor/build0.prop:$(TARGET_COPY_OUT_VENDOR)/build0.prop \
    vendor/huawei/P30/proprietary/vendor/build1.prop:$(TARGET_COPY_OUT_VENDOR)/build1.prop \
    vendor/huawei/P30/proprietary/vendor/build2.prop:$(TARGET_COPY_OUT_VENDOR)/build2.prop \
    vendor/huawei/P30/proprietary/vendor/build3.prop:$(TARGET_COPY_OUT_VENDOR)/build3.prop \
    vendor/huawei/P30/proprietary/vendor/build4.prop:$(TARGET_COPY_OUT_VENDOR)/build4.prop \
    vendor/huawei/P30/proprietary/vendor/build5.prop:$(TARGET_COPY_OUT_VENDOR)/build5.prop \
    vendor/huawei/P30/proprietary/vendor/build6.prop:$(TARGET_COPY_OUT_VENDOR)/build6.prop \
    vendor/huawei/P30/proprietary/vendor/build7.prop:$(TARGET_COPY_OUT_VENDOR)/build7.prop \
    vendor/huawei/P30/proprietary/vendor/build8.prop:$(TARGET_COPY_OUT_VENDOR)/build8.prop \
    vendor/huawei/P30/proprietary/vendor/build9.prop:$(TARGET_COPY_OUT_VENDOR)/build9.prop \
    vendor/huawei/P30/proprietary/vendor/custom0.conf:$(TARGET_COPY_OUT_VENDOR)/custom0.conf \
    vendor/huawei/P30/proprietary/vendor/custom1.conf:$(TARGET_COPY_OUT_VENDOR)/custom1.conf \
    vendor/huawei/P30/proprietary/vendor/custom2.conf:$(TARGET_COPY_OUT_VENDOR)/custom2.conf \
    vendor/huawei/P30/proprietary/vendor/custom3.conf:$(TARGET_COPY_OUT_VENDOR)/custom3.conf \
    vendor/huawei/P30/proprietary/vendor/custom4.conf:$(TARGET_COPY_OUT_VENDOR)/custom4.conf \
    vendor/huawei/P30/proprietary/vendor/custom5.conf:$(TARGET_COPY_OUT_VENDOR)/custom5.conf \
    vendor/huawei/P30/proprietary/vendor/custom6.conf:$(TARGET_COPY_OUT_VENDOR)/custom6.conf \
    vendor/huawei/P30/proprietary/vendor/custom7.conf:$(TARGET_COPY_OUT_VENDOR)/custom7.conf \
    vendor/huawei/P30/proprietary/vendor/custom8.conf:$(TARGET_COPY_OUT_VENDOR)/custom8.conf \
    vendor/huawei/P30/proprietary/vendor/custom9.conf:$(TARGET_COPY_OUT_VENDOR)/custom9.conf \
    vendor/huawei/P30/proprietary/vendor/lib/drm/libdrmwvmplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmwvmplugin.so \
    vendor/huawei/P30/proprietary/vendor/lib/hw/audio.a2dp.blueangel.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.a2dp.blueangel.so \
    vendor/huawei/P30/proprietary/vendor/lib/hw/bluetooth.blueangel.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/bluetooth.blueangel.so \
    vendor/huawei/P30/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L3.so \
    vendor/huawei/P30/proprietary/vendor/lib/libwvdrm_L3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L3.so \
    vendor/huawei/P30/proprietary/vendor/lib/libwvm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvm.so \
    vendor/huawei/P30/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/huawei/P30/proprietary/vendor/lib/mediadrm/libmockdrmcryptoplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libmockdrmcryptoplugin.so \
    vendor/huawei/P30/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    vendor/huawei/P30/proprietary/vendor/operator/app/Viber/arm/Viber.odex:$(TARGET_COPY_OUT_VENDOR)/operator/app/Viber/arm/Viber.odex \
    vendor/huawei/P30/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin \
    vendor/huawei/P30/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin \
    vendor/huawei/P30/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin \
    vendor/huawei/P30/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin \
    vendor/huawei/P30/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin \
    vendor/huawei/P30/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin \
    vendor/huawei/P30/proprietary/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin:$(TARGET_COPY_OUT_VENDOR)/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin
